### ISSUE TITLE
can i update the maxValue?

### ISSUE THREAD

**Issue by vuuihc** [lugolabs/circles#41]
i want to update the value and the maxvalue at the same time

**Comment by rtsinani** [comment]
Yes, by passing it as an option when creating a Circles object, e.g:

```js
Circles.create({
  id:         'circles',
  value:      34,
  maxValue:   200,
  radius:     60,
  width:      10
});
```

**Comment by Professor-Z** [comment]
Sorry but I think you misread my question. I want to update it **after** created the object.For example, I  want my circle to has different maxValue with different value, I create a circles object at first, then after some operation such as ajxa, the value be updated, and I want the maxValue updated at the same time, is there any api can help me do this?

**Comment by ViRuSTriNiTy** [comment]
@Professor-Z I think you can just call Circles.create() again when you need to update the values.

**Comment by ViRuSTriNiTy** [comment]
@Professor-Z There's a better way to handle the max value issue. Just use a 0 to 100 percent range by setting maxValue to 100. This avoids the need to update maxValue as you now need to just pass in the current value as percent value. Also, i noticed when using high maxValues the animations will be pretty sluggish, so this will be also fixed with a 0 to 100 percent range.
